sudo: false
os:
  - linux
  - osx
language: node_js
arch:
  - amd64
  - ppc64le
node_js:
  - node
  - '9'
  - '8'
  - '7'
  - '6'
  - '5'
  - '4'
  - '0.12'
  - '0.10'
 # exlcude unsupport power jobs node 0.10,0.12
 matrix:
   exclude:
     - arch: ppc64le
       node: 0.10
     - arch: ppc64le
       node: 0.12
